name: GitHub Pages

on:
  push:
    branches:
      - www/master
  pull_request:
    branches:
      - www/master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build table plugin
        working-directory: ./plugins/gatsby-remark-responsive-tables
        run: |
          npm install
          npm run build

      - name: Build site
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/www/master' }}
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: www/production
          publish_dir: ./public
          cname: masb.thealbert.dev
