name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          envkey_REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          envkey_REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          envkey_REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          envkey_REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          envkey_REACT_APP_MESSAGING_APP_ID: ${{ secrets.REACT_APP_MESSAGING_APP_ID }}
          envkey_REACT_APP_MESSAGING_MEASUREMENT_ID: ${{ secrets.REACT_APP_MESSAGING_MEASUREMENT_ID }}


      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: thealbertdev/maqa-app-production
          publish_branch: master
          publish_dir: ./dist
          cname: masb.thealbert.dev
